# -*- coding: utf-8 -*-
"""whisper_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OtAVXAsK416qQbrHTxfaKLoROwgTPiEu
"""

! pip install git+https://github.com/openai/whisper.git
! pip install jiwer

import whisper
import os
import subprocess
import sys
import pickle
from whisper.utils import write_srt, write_vtt

model = whisper.load_model("large")

def video2mp3(video_file, output_ext="mp3"):
    filename, ext = os.path.splitext(video_file)
    subprocess.call(["ffmpeg", "-y", "-i", video_file, f"{filename}.{output_ext}"], 
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.STDOUT)
    return f"{filename}.{output_ext}"

def translate(input_video, task="translate", language='en'):

    audio_file = video2mp3(input_video)
    
    options = dict(beam_size=5, best_of=5, language=language)
    translate_options = dict(task=task, **options)
    result = model.transcribe(audio_file,**translate_options)

    output_dir = '/content/'
    audio_path = audio_file.split(".")[0]

    with open(os.path.join(output_dir, audio_path + ".vtt"), "w") as vtt:
      write_vtt(result["segments"], file=vtt)

    subtitle = audio_path + ".vtt"
    output_video = audio_path + "_subtitled.mp4"

    os.system(f"ffmpeg -i {input_video} -vf subtitles={subtitle} {output_video}")

    return output_video

def runcmd(cmd, verbose = False, *args, **kwargs):

    process = subprocess.Popen(
        cmd,
        stdout = subprocess.PIPE,
        stderr = subprocess.PIPE,
        text = True,
        shell = True
    )
    std_out, std_err = process.communicate()
    if verbose:
        print(std_out.strip(), std_err)
    pass

url = "https://d3cvwyf9ksu0h5.cloudfront.net/answer-1577455830_203596.mp4"
input_video = "geometry.mp4"

runcmd(f"wget -O {input_video} {url}", verbose=True)

# audio_file = video2mp3(input_video)

output_video = translate(input_video)

import pickle
with open('output.pkl', 'wb') as f:  # Python 3: open(..., 'wb')
    pickle.dump(output_video, f)

## download videos

# !wget -O chemistry_QA.mp4 https://d3cvwyf9ksu0h5.cloudfront.net/answer-1554740086.mp4
# !wget -O geometry_QA.mp4 https://d3cvwyf9ksu0h5.cloudfront.net/answer-1577455830_203596.mp4

## inspect video files

# !ffprobe -hide_banner /content/chemistry_QA.mp4
# !ffprobe -hide_banner /content/geometry_QA.mp4

## covert video files to mp3 audio format

# !ffmpeg -i chemistry_QA.mp4 -acodec libmp3lame chemistry_QA.mp3
# !ffmpeg -i geometry_QA.mp4 -acodec libmp3lame geometry_QA.mp3

